# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hitchhiker.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hitchhiker.proto\x12\nhitchhiker\"\x14\n\x12GetSourceIdRequest\"(\n\x13GetSourceIdResponse\x12\x11\n\tsource_id\x18\x01 \x01(\t\"@\n\x13GetDownloadsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x02 \x01(\t\")\n\x14GetDownloadsResponse\x12\x11\n\tfile_list\x18\x01 \x03(\t\";\n\x13\x44ownloadFileRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tfile_list\x18\x02 \x03(\t\"F\n\x04\x46ile\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x62lob\x18\x04 \x01(\x0c\"6\n\x14\x44ownloadFileResponse\x12\x1e\n\x04\x66ile\x18\x01 \x03(\x0b\x32\x10.hitchhiker.File\"T\n\x14MarkDeliveredRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65stination_id\x18\x02 \x01(\t\x12\x11\n\tfile_list\x18\x03 \x03(\t\"\x17\n\x15MarkDeliveredResponse2\xe6\x02\n\x10HitchhikerSource\x12P\n\x0bGetSourceId\x12\x1e.hitchhiker.GetSourceIdRequest\x1a\x1f.hitchhiker.GetSourceIdResponse\"\x00\x12S\n\x0cGetDownloads\x12\x1f.hitchhiker.GetDownloadsRequest\x1a .hitchhiker.GetDownloadsResponse\"\x00\x12S\n\x0c\x44ownloadFile\x12\x1f.hitchhiker.DownloadFileRequest\x1a .hitchhiker.DownloadFileResponse\"\x00\x12V\n\rMarkDelivered\x12 .hitchhiker.MarkDeliveredRequest\x1a!.hitchhiker.MarkDeliveredResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hitchhiker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSOURCEIDREQUEST']._serialized_start=32
  _globals['_GETSOURCEIDREQUEST']._serialized_end=52
  _globals['_GETSOURCEIDRESPONSE']._serialized_start=54
  _globals['_GETSOURCEIDRESPONSE']._serialized_end=94
  _globals['_GETDOWNLOADSREQUEST']._serialized_start=96
  _globals['_GETDOWNLOADSREQUEST']._serialized_end=160
  _globals['_GETDOWNLOADSRESPONSE']._serialized_start=162
  _globals['_GETDOWNLOADSRESPONSE']._serialized_end=203
  _globals['_DOWNLOADFILEREQUEST']._serialized_start=205
  _globals['_DOWNLOADFILEREQUEST']._serialized_end=264
  _globals['_FILE']._serialized_start=266
  _globals['_FILE']._serialized_end=336
  _globals['_DOWNLOADFILERESPONSE']._serialized_start=338
  _globals['_DOWNLOADFILERESPONSE']._serialized_end=392
  _globals['_MARKDELIVEREDREQUEST']._serialized_start=394
  _globals['_MARKDELIVEREDREQUEST']._serialized_end=478
  _globals['_MARKDELIVEREDRESPONSE']._serialized_start=480
  _globals['_MARKDELIVEREDRESPONSE']._serialized_end=503
  _globals['_HITCHHIKERSOURCE']._serialized_start=506
  _globals['_HITCHHIKERSOURCE']._serialized_end=864
# @@protoc_insertion_point(module_scope)
