# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hitchhiker.proto for package 'hitchhiker'

require 'grpc'
require 'hitchhiker_pb'

module Hitchhiker
  module HitchhikerSource
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'hitchhiker.HitchhikerSource'

      rpc :GetSourceId, ::Hitchhiker::GetSourceIdRequest, ::Hitchhiker::GetSourceIdResponse
      rpc :GetDownloads, ::Hitchhiker::GetDownloadsRequest, ::Hitchhiker::GetDownloadsResponse
      rpc :DownloadFile, ::Hitchhiker::DownloadFileRequest, ::Hitchhiker::DownloadFileResponse
      rpc :MarkDelivered, ::Hitchhiker::MarkDeliveredRequest, ::Hitchhiker::MarkDeliveredResponse
    end

    Stub = Service.rpc_stub_class
  end
end
